import Head from 'next/head'
import { Home as HomeController } from '../src/components/Home'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ordering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeController />
    </>
  )
}
